name: ci

on:
  push:
    branches:
      - 'master'

env:
  GKE_CLUSTER: experiment
  GKE_ZONE: asia-southeast1
  IMAGE_NAME: mainey/golang-ping
  DEPLOYMENT_NAME: go-app
  DEPLOYMENT_NS: go-njs

jobs:
  go-test:
    name: Test Go
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
      - name: Test
        run: go test -v .

  build-dockerx:
    name: Build, test, and Push
    runs-on: ubuntu-latest
    needs: go-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

  rollout-gke:
    name: Rollout deployment on GKE
    runs-on: ubuntu-latest
    needs: build-dockerx
    steps:
      - name: Auth Google
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
      - name: Rollout restart deployment
        run: |-
          kubectl rollout restart deployment/$DEPLOYMENT_NAME -n $DEPLOYMENT_NS
          kubectl rollout status deployment/$DEPLOYMENT_NAME -n $DEPLOYMENT_NS
